gre/components/nsINIProcessor.js (etc.)
JavaScript strict warning: resource://gre/components/nsINIProcessor.js,
line 147:
etc.
SyntaxError: octal literals and octal escape sequences are deprecated
https://bugzilla.mozilla.org/show_bug.cgi?id=1248252